//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod articles;
pub mod categories;
pub mod member_bills;
pub mod member_teams;
pub mod members;
pub mod system_action_logs;
pub mod system_caches;
pub mod system_depts;
pub mod system_dict_data;
pub mod system_dicts;
pub mod system_login_logs;
pub mod system_menus;
pub mod system_role_menus;
pub mod system_roles;
pub mod system_users;
