//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "members")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub unique_code: String,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub mobile: String,
    #[sea_orm(column_type = "Text")]
    pub nickname: String,
    #[sea_orm(column_type = "Text")]
    pub avatar: String,
    #[sea_orm(column_type = "Text")]
    pub password: String,
    #[sea_orm(column_type = "Text")]
    pub salt: String,
    pub sex: i32,
    pub balance: Decimal,
    pub integral: i32,
    #[sea_orm(column_type = "Text")]
    pub remark: String,
    pub status: i32,
    pub is_promoter: i32,
    #[sea_orm(column_type = "Text")]
    pub last_login_ip: String,
    #[sea_orm(column_type = "custom(\"DATETIME\")", nullable)]
    pub last_login_time: Option<String>,
    #[sea_orm(column_type = "custom(\"DATETIME\")")]
    pub created_at: String,
    #[sea_orm(column_type = "custom(\"DATETIME\")")]
    pub updated_at: String,
    #[sea_orm(column_type = "custom(\"DATETIME\")", nullable)]
    pub deleted_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::member_bills::Entity")]
    MemberBills,
}

impl Related<super::member_bills::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MemberBills.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
