//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "system_menus")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub parent_id: i32,
    pub r#type: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub icon: String,
    #[sea_orm(column_type = "Text")]
    pub router_name: String,
    #[sea_orm(column_type = "Text")]
    pub router_component: String,
    #[sea_orm(column_type = "Text")]
    pub router_path: String,
    #[sea_orm(column_type = "Text")]
    pub redirect: String,
    #[sea_orm(column_type = "Text")]
    pub link: String,
    #[sea_orm(column_type = "Text")]
    pub iframe: String,
    #[sea_orm(column_type = "Text")]
    pub btn_auth: String,
    #[sea_orm(column_type = "Text")]
    pub api_url: String,
    #[sea_orm(column_type = "Text")]
    pub api_method: String,
    pub is_hide: i32,
    pub is_keep_alive: i32,
    pub is_affix: i32,
    pub sort: i32,
    #[sea_orm(column_type = "custom(\"DATETIME\")")]
    pub created_at: String,
    #[sea_orm(column_type = "custom(\"DATETIME\")")]
    pub updated_at: String,
    #[sea_orm(column_type = "custom(\"DATETIME\")", nullable)]
    pub deleted_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::system_action_logs::Entity")]
    SystemActionLogs,
    #[sea_orm(has_many = "super::system_role_menus::Entity")]
    SystemRoleMenus,
}

impl Related<super::system_action_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemActionLogs.def()
    }
}

impl Related<super::system_role_menus::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemRoleMenus.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
